version: '3'

vars:
  USER_ID:
    sh: id -u
  GROUP_ID:  
    sh: id -g

tasks:
  dev:
    desc: Start development environment
    env:
      USER_ID: '{{.USER_ID}}'
      GROUP_ID: '{{.GROUP_ID}}'
    cmds:
      - docker compose -f docker-compose.dev.yml up --build

  stop:
    desc: Stop development environment
    cmds:
      - docker compose -f docker-compose.dev.yml down
