FROM golang:1.24-alpine

# Install air for hot reload
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Expose port
EXPOSE 8888

# Start air for hot reload
CMD ["air"]